# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

matrix:
    include:
        - php: 5.6
          env: COVERAGE_BUILD=true
        - php: 7.0
        - php: hhvm

install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$COVERAGE_BUILD" != true ]; then phpenv config-rm xdebug.ini; fi
    - composer self-update
    - composer install --prefer-source

script: bin/phpunit `if [ "$COVERAGE_BUILD" = true ]; then echo "--coverage-clover build/clover.xml"; fi`

after_success:
    - if [ "$COVERAGE_BUILD" = true ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$COVERAGE_BUILD" = true ]; then php ocular.phar code-coverage:upload --format=php-clover build/clover.xml; fi
