# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 5.6
    - 7.0
    - hhvm

install:
    - composer self-update
    - composer install --prefer-source

script: bin/phpunit
