# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

doctrine:
    dbal:
        charset: UTF8
        dbname: "%database_name%"
        driver: pdo_mysql
        host: "%database_host%"
        password: "%database_password%"
        port: "%database_port%"
        user: "%database_user%"
        server_version: "%database_version%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        repository_factory: lug.translation.repository.doctrine.orm.factory

a2lix_translation_form:
    manager_registry: doctrine

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
