# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true
            repository_factory: lug.translation.repository.doctrine.mongodb.factory

a2lix_translation_form:
    manager_registry: doctrine_mongodb

stof_doctrine_extensions:
    mongodb:
        default:
            timestampable: true
