# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

imports:
    - { resource: config_dev.yml }
    - { resource: bundles/test/framework.yml }
    - { resource: bundles/test/web_profiler.yml }
