# This file is part of the Lug package.
#
# (c) Eric GELOEN <geloen.eric@gmail.com>
#
# For the full copyright and license information, please read the LICENSE
# file that was distributed with this source code.

lug_admin:
    resource: "@LugAdminBundle/Resources/config/routing.yml"

lug_locale:
    resource: "@LugLocaleBundle/Resources/config/routing/routing.yml"
